require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
  # IgnoredMethods: ['describe', 'context']

Style/Documentation:
  Enabled: false
